### ISSUE TITLE
how to Show Dev Tools

### ISSUE THREAD

**Issue by gaetandezeiraud** [edgesharp/EdgeSharp#3]
I have tried to do like in Chromely. But it doesn't seems to be the way to go. Because `_config.DevToolsUrl` doesn't exist. And I don't find a way to access to the ICoreWebView2 in order to call the `OpenDevToolsWindow()` in WebView2.

**Comment by mikeychowy** [comment]
You may found this out already, but how about just pressing f12? 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug?tabs=devtools

Or maybe use devtools protocol? 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/chromium-devtools-protocol
