### ISSUE TITLE
How to swap webview2 version

### ISSUE THREAD

**Issue by mikeychowy** [edgesharp/EdgeSharp#5]
@mattkol, I want to use newest stable version of webview2, how can I do that? Do I just have to provide a fixed version of it using this option? https://github.com/edgesharp/EdgeSharp/blob/af12bba0377510dddc6d4a2f68201afd262a4aad/src/EdgeSharp.Core/Configuration/WebView2CreationOptions.cs#L53

**Comment by mattkol** [comment]
@mikeychowy I am assuming you are referring to the runtime.

You either install the latest on the destination machine or you set a fixed one using the configuration option. If there is nothing set in the configuration, it reverts to what is on the machine.

**Comment by mikeychowy** [comment]
Thank you very much, and I was indeed referring to the Webview2 runtime.
