### ISSUE TITLE
Support net framework?

### ISSUE THREAD

**Issue by weianweigan** [edgesharp/EdgeSharp#8]
Hi, this is a awsome project.
I want to use it in my work, but i found that it cannot used in .net framework's wpf project.
So i forked it and add net461 to TargetFrameworks.

This is my [commit](https://github.com/weianweigan/EdgeSharp/commit/e1263d224559e5e85d141c0fdf19332bb86a3928#diff-8299824c18eff3f511b73e207dbcf851cb3386028a800ca3a8cd47b0b6b7e588).
I changed a few lines of code to compile and passed testcase.
It passed unittests but I don't konw if there is some other problems when i use it in .net framework.
If there is no major problem, Could i create a pr for this?

**Comment by mattkol** [comment]
@weianweigan sure, please create the PR, it would help other developers using .NET Framework.
Thanks.
